name: Deploy to EC2

on:
  push:
    branches: [ "main" ]   # runs only when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/chatbot || git clone https://github.com/${{ github.repository }}.git chatbot
          cd ~/chatbot
          git pull origin main
          npm install
          pm2 restart server.js || pm2 start server.js
        EOF
